import Head from 'next/head'
import Signup from '../components/signup'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chirpt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Signup />
      </main>
    </div>
  )
}
